### ISSUE TITLE
plain grey screen

### ISSUE THREAD

**Issue by Foxxey** [y9x/clientpp#5]
everytime i start the "Client.v1.0.0-beta.3.exe" i get this plane grey window... and krunker doesnt start

https://prnt.sc/44HsWWwdD0jv

**Comment by ghost** [comment]
The window handle's background is set to that color and is visible before WebView2 is loaded. Here are some reasons why WebView2 wouldn't load:
- Internet connection
- Bad/outdated install of WebView2
- JavaScript failure

**Comment by Foxxey** [comment]
I updated and not its stuck on the krunker loading screen. How do I open console?

**Comment by ghost** [comment]
> I updated and not its stuck on the krunker loading screen. How do I open console?

You're looking for Devtools. It's CTRL + SHIFT + I.
