### ISSUE TITLE
Choppy Gameplay

### ISSUE THREAD

**Issue by grafixdevloper** [y9x/clientpp#7]
I have a good pc, when i use the official client I get around 250 fps on max graphical settings. When I turned on the uncapped fps option in this client I was getting like 900fps but it was chopyy like it was lagging, the stats showed 900fps+ but I was seeing 15fps

**Comment by ghost** [comment]
@grafixdevloper 
This is a common issue with the client. I am not sure how to go about fixing this. Here's some alternatives:
- Disable in-game tweaks such as Aim Freeze Fix (this setting artificially changes FPS and we already fix the bug)
- Keep FPS capped (you should be able to get the maximum FPS with VSync enabled without any input lag)
- Increase your monitors frequency
- Use another client that offers a more comfortable amount of FPS (perhaps 900+ ticks/second is simply too much)
